[major-change]
second_label = "final-comment-period"
meeting_label = "to-announce"
# can be found by looking for the first number in URLs, e.g. https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler
zulip_stream = 233931
zulip_ping = "T-compiler"
